//
// Created by bialger on 21.02.24.
//

#ifndef WEATHER_FORECAST_LIB_FORECAST_GEOCODER_H_
#define WEATHER_FORECAST_LIB_FORECAST_GEOCODER_H_

class Geocoder {

};

#endif //WEATHER_FORECAST_LIB_FORECAST_GEOCODER_H_
